### ISSUE TITLE
Support Protocols with recursive structures?

### ISSUE THREAD

**Issue by knoll01** [billvaglienti/ProtoGen#93]
I am new to ProtoGen and I am trying to implement a protocol that is based on TLVs. The protocol can have TLVs and sub-TLVs and sub-sub-TLVs, etc. Could ProtoGen support this by defining a TLV as a packet and using the useInOtherPackets flag, or is there a better approach?

**Comment by billvaglienti** [comment]
Yes, it should be able to do that.

The approach you suggest is how I would go about it. You could also define
each TLV as a structure rather than a packet. The choice of which method to
use depends on if the sub-TLVs will be sent standalone in some
circumstances, in which case you would define them as packets. If they will
only ever be subordinate to a larger TLV them you could optionally define
the sub TLVs as structures rather than packets.

regards,

Bill Vaglienti
541 399 7883
4207 Post Canyon
Hood River OR, 97031

**Comment by knoll01** [comment]
Thanks for the quick response. I will give it a try later this week.
